os: linux
dist: bionic
language: python
branches:
  only:
    - master
services:
  - docker
env:
  global:
    - VERSION=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in service_account.json.enc -out service_account.json -d

  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl

  - gcloud auth activate-service-account --key-file service_account.json

  - gcloud config set project simple-k8s-6689
  - gcloud config set compute/zone asia-east1-c
  - gcloud container clusters get-credentials my-first-cluster

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "skipping tests"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
